<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ros_speech_recognition</name>
  <version>2.1.31</version>
  <description>ROS2 wrapper for Python SpeechRecognition library</description>
  <url type="website">https://pypi.python.org/pypi/SpeechRecognition/</url>

  <maintainer email="tsubaki@jsk.t.u-tokyo.ac.jp">Tsubaki Tsubaki</maintainer>
  <author email="furushchev@jsk.imi.i.u-tokyo.ac.jp">Yuki Furuta</author>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>ament_cmake_python</build_depend>

  <exec_depend>action_msgs</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>audio_capture</exec_depend>
  <exec_depend>audio_common_msgs</exec_depend>
  <exec_depend>flac</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>launch_xml</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sound_play</exec_depend>
  <exec_depend>sound_play_msgs</exec_depend>
  <exec_depend>sound-theme-freedesktop</exec_depend>
  <exec_depend>speech_recognition_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
