{
 "title": "Fetch15",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Battery Charge Percent",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "battery",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_name", "operator": "=", "value": "Main Battery" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "receive bps",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_states",
     "select": [
      [
       { "params": [ "bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "receive" }
     ]
    },
    {
     "alias": "transmit bps",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_states",
     "select": [
      [
       { "params": [ "bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "transmit" }
     ]
    }
   ]
  },
  {
   "title": "Base Translation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "tranlation.x",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "base_link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "map" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "x" }
     ]
    },
    {
     "alias": "tranlation.y",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "base_link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "map" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "y" }
     ]
    }
   ]
  },
  {
   "title": "Head Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "head_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "head_pan_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "head_tilt_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "head_tilt_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    }
   ]
  },
  {
   "title": "Arm Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "shoulder_pan_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "shoulder_lift_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "upperarm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "upperarm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "elbow_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "forearm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "wrist_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "wrist_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    }
   ]
  },
  {
   "title": "Torso Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "torso_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "torso_lift_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    }
   ]
  },
  {
   "title": "Wheel Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    }
   ]
  },
  {
   "title": "Base Rotation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "rotation.z",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "base_link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "map" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rotation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "theta" }
     ]
    }
   ]
  },
  {
   "title": "Head Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "head_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "head_pan_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "head_tilt_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "head_tilt_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    }
   ]
  },
  {
   "title": "Arm Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "shoulder_pan_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "shoulder_lift_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "upperarm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "upperarm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "elbow_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "forearm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "wrist_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "wrist_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    }
   ]
  },
  {
   "title": "Torso Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "torso_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "torso_lift_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    }
   ]
  },
  {
   "title": "Wheel Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    }
   ]
  },
  {
   "title": "EE translation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "translation.x",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_transform",
     "select": [
      [
       { "params": [ "gripper_link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "base_link" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "x" }
     ]
    },
    {
     "alias": "translation.y",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_transform",
     "select": [
      [
       { "params": [ "gripper_link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "base_link" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "y" }
     ]
    },
    {
     "alias": "translation.z",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_transform",
     "select": [
      [
       { "params": [ "gripper_link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "base_link" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "z" }
     ]
    }
   ]
  }
 ]
}