{
 "title": "PR1012",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Battery charge percent",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "battery 0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "query": "SELECT mean(\"charge_percent\") FROM \"battery_states\" WHERE (\"battery_id\" = '0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "battery 1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "battery 2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "battery 3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "battery 0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "battery 1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "battery 2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "battery 3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Battery current",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "battery 0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "battery 1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "battery 2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "battery 3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "battery 0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "battery 1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "battery 2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "battery 3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "receive bps",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_states",
     "select": [
      [
       { "params": [ "bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "receive" }
     ]
    },
    {
     "alias": "transmit bps",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_states",
     "select": [
      [
       { "params": [ "bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "transmit" }
     ]
    }
   ]
  },
  {
   "title": "Base Translation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "translation.x",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "base_footprint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "map" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "x" }
     ]
    },
    {
     "alias": "translation.y",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "base_footprint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "map" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "y" }
     ]
    }
   ]
  },
  {
   "title": "Head Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "head_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "head_pan_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "head_tilt_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "head_tilt_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    }
   ]
  },
  {
   "title": "Left Arm Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "l_elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_elbow_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "l_forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_forearm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "l_shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_shoulder_lift_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "l_shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_shoulder_pan_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "l_upper_arm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_upper_arm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "l_wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_wrist_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "l_wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_wrist_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    }
   ]
  },
  {
   "title": "Right Arm Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "r_elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_elbow_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "r_forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_forearm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "r_shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_shoulder_lift_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "r_shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_shoulder_pan_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "r_upper_arm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_upper_arm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "r_wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_wrist_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "r_wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_wrist_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    }
   ]
  },
  {
   "title": "Torso Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "torso_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "torso_lift_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    }
   ]
  },
  {
   "title": "Wheel Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "bl_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "bl_caster_l_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "bl_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "bl_caster_r_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "bl_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "bl_caster_rotation_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "br_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "br_caster_l_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "br_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "br_caster_r_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "br_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "br_caster_rotation_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "fl_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fl_caster_l_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "fl_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fl_caster_r_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "fl_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fl_caster_rotation_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "fr_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fr_caster_l_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "fr_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fr_caster_r_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    },
    {
     "alias": "fr_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fr_caster_rotation_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "position" }
     ]
    }
   ]
  },
  {
   "title": "Base rotation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "rotation.z",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "base_footprint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "map" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rotation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "theta" }
     ]
    }
   ]
  },
  {
   "title": "Head Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "head_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "head_pan_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "head_tilt_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "head_tilt_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    }
   ]
  },
  {
   "title": "Left Arm Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "l_elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_elbow_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "l_forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_forearm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "l_shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_shoulder_lift_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "l_shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_shoulder_pan_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "l_upper_arm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_upper_arm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "l_wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_wrist_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "l_wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "l_wrist_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    }
   ]
  },
  {
   "title": "Right Arm Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "r_elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_elbow_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "r_forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_forearm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "r_shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_shoulder_lift_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "r_shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_shoulder_pan_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "r_upper_arm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_upper_arm_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "r_wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_wrist_flex_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "r_wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "r_wrist_roll_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    }
   ]
  },
  {
   "title": "Torso Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "torso_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "torso_lift_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    }
   ]
  },
  {
   "title": "Wheel Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "bl_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "bl_caster_l_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "bl_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "bl_caster_r_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "bl_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "bl_caster_rotation_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "br_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "br_caster_l_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "br_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "br_caster_r_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "br_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "br_caster_rotation_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "fl_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fl_caster_l_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "fl_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fl_caster_r_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "fl_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fl_caster_rotation_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "fr_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fr_caster_l_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "fr_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fr_caster_r_wheel_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    },
    {
     "alias": "fr_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "fr_caster_rotation_joint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "effort" }
     ]
    }
   ]
  },
  {
   "title": "EE Translation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 24 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "left translation.x",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_transform",
     "select": [
      [
       { "params": [ "l_gripper_tool_frame" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "base_footprint" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "x" }
     ]
    },
    {
     "alias": "left translation.y",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_transform",
     "select": [
      [
       { "params": [ "l_gripper_tool_frame" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "base_footprint" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "y" }
     ]
    },
    {
     "alias": "left  translation.z",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_transform",
     "select": [
      [
       { "params": [ "l_gripper_tool_frame" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "base_footprint" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "z" }
     ]
    },
    {
     "alias": "right translation.x",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_transform",
     "select": [
      [
       { "params": [ "r_gripper_tool_frame" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "base_footprint" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "x" }
     ]
    },
    {
     "alias": "right translation.y",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_transform",
     "select": [
      [
       { "params": [ "r_gripper_tool_frame" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "base_footprint" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "y" }
     ]
    },
    {
     "alias": "right translation.z",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_transform",
     "select": [
      [
       { "params": [ "r_gripper_tool_frame" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "frame_id", "operator": "=", "value": "base_footprint" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "translation" },
      { "condition": "AND", "key": "field", "operator": "=", "value": "z" }
     ]
    }
   ]
  }
 ]
}