#!/usr/bin/env python
# -*- encoding: utf-8 -*-

import rospy

from sound_navigator.sound_navigator_node import SoundNavigatorNode


if __name__ == '__main__':

    rospy.init_node('sound_navigator')
    node = SoundNavigatorNode()
    rospy.spin()
