# Define the goal
string space # space name, identify the chat room
string message_type # supports "text" or "card".
string content # if message_type is text, content is just string type. if message_type is card, content is expetcted json style below. See https://developers.google.com/chat/api/guides/message-formats/cards for details.
##### RAW JSON TEXT EXAMPLE #####
      # "sections": [
      #   {
      #     "widgets": [
      #       {
      #         "image": { "imageUrl": "https://..." }
      #       },
      #       {
      #         "buttons": [
      #           {
      #             "textButton": {
      #               "text": "OPEN IN GOOGLE MAPS",
      #               "onClick": {
      #                 "openLink": {
      #                   "url": "https://..."
      #                 }
      #               }
      #             }
      #           }
      #         ]
      #       }
      #     ]
      #   }
      # ]
### END RAW JSON TEXT EXAMPLE ###
---
# Define the result
bool done
---
# Define a feedback message
string status
