#!/bin/bash

# Argument check
if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <serial_number> <symlink_name>"
  echo "  <serial_number> : The serial number of your USB-Serial troubleshooter (e.g., 001A02F2046C)"
  echo "  <symlink_name>  : The name to create as a symbolic link in /dev (e.g., usb_serial_troubleshooter1)"
  exit 1
fi

SERIAL_NUMBER="$1"
SYMLINK_NAME="$2"

RULES_DIR="/etc/udev/rules.d"
TEMPLATE_PATH="$(rospack find century_ros)/udev/90-usb-serial-troubleshooter.rules.template"
RULES_PATH="$RULES_DIR/90-usb-serial-troubleshooter.rules"

echo ""
echo "This script generates udev rules for USB-Serial troubleshooter"
echo "Serial number : $SERIAL_NUMBER"
echo "Symlink name  : $SYMLINK_NAME"
echo "Output rule   : $RULES_PATH"
echo ""

sudo bash -c "sed \
  -e 's|{{SERIAL}}|$SERIAL_NUMBER|' \
  -e 's|{{SYMLINK}}|$SYMLINK_NAME|' \
  '$TEMPLATE_PATH' > '$RULES_PATH'"

echo ""
echo "Restarting udev"
echo ""
sudo udevadm control --reload
sudo udevadm trigger

echo "udev rules installed"
