image_width: 320
image_height: 240
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [ 239.31855,    0.     ,  174.70228,
            0.     ,  238.39058,  113.35511,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.366597, 0.138354, 0.000645, 0.001620, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 194.37418,    0.     ,  181.68859,    0.     ,
            0.     ,  213.5239 ,  111.92391,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
